#!/usr/bin/env bash
set -Eeuo pipefail

INSTALLER_VERSION="0.1.0"
SERVICE_NAME="xaccel-node"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/xaccel-node"
DATA_DIR="/var/lib/xaccel-node"
LOG_DIR="/var/log/xaccel-node"
SYSTEMD_UNIT="/etc/systemd/system/${SERVICE_NAME}.service"
IDENTITY_FILE="${DATA_DIR}/identity.json"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
HEALTH_URL="http://127.0.0.1:9876/health"

BOOTSTRAP_URL=""
BOOTSTRAP_TOKEN=""
CHANNEL="stable"
OPEN_FIREWALL="0"
DRY_RUN="0"

usage() {
  cat <<'USAGE'
Usage:
  install.sh --bootstrap-url URL --bootstrap-token TOKEN [options]

Options:
  --bootstrap-url URL     Backend bootstrap API URL.
  --bootstrap-token TOKEN One-time token generated by the backend.
  --channel CHANNEL       Release channel. Default: stable.
  --open-firewall         Try to open the node port with ufw/firewalld.
  --dry-run               Run preflight only and print planned actions.
  -h, --help              Show this help.
USAGE
}

log() {
  printf '[xaccel-installer] %s\n' "$*"
}

fail() {
  printf '[xaccel-installer] ERROR: %s\n' "$*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bootstrap-url)
      BOOTSTRAP_URL="${2:-}"
      shift 2
      ;;
    --bootstrap-token)
      BOOTSTRAP_TOKEN="${2:-}"
      shift 2
      ;;
    --channel)
      CHANNEL="${2:-}"
      shift 2
      ;;
    --open-firewall)
      OPEN_FIREWALL="1"
      shift
      ;;
    --dry-run)
      DRY_RUN="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

require_root() {
  [[ "$(id -u)" == "0" ]] || fail "please run as root"
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "x86_64" ;;
    aarch64|arm64) echo "aarch64" ;;
    *) fail "unsupported arch: $(uname -m)" ;;
  esac
}

detect_ips() {
  ip -o -4 addr show scope global | awk '{ split($4, a, "/"); print a[1] }' | paste -sd, -
}

detect_ips_json() {
  ip -o -4 addr show scope global |
    awk '
      BEGIN { printf "["; first=1 }
      {
        split($4, a, "/")
        if (!first) { printf "," }
        printf "\"%s\"", a[1]
        first=0
      }
      END { printf "]" }
    '
}

preflight() {
  require_root
  command -v systemctl >/dev/null 2>&1 || fail "systemd is required"
  command -v curl >/dev/null 2>&1 || fail "curl is required"
  command -v ip >/dev/null 2>&1 || fail "iproute2 is required"
  [[ -n "$BOOTSTRAP_URL" ]] || fail "--bootstrap-url is required"
  [[ -n "$BOOTSTRAP_TOKEN" ]] || fail "--bootstrap-token is required"
}

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

bootstrap() {
  local hostname arch kernel ips_json payload response
  hostname="$(hostname)"
  arch="$(detect_arch)"
  kernel="$(uname -r)"
  ips_json="$(detect_ips_json)"

  payload=$(
    cat <<JSON
{
  "bootstrap_token": "$(json_escape "$BOOTSTRAP_TOKEN")",
  "hostname": "$(json_escape "$hostname")",
  "os": "linux",
  "arch": "$(json_escape "$arch")",
  "kernel": "$(json_escape "$kernel")",
  "ips": $ips_json,
  "installer_version": "$INSTALLER_VERSION"
}
JSON
  )

  log "bootstrap node identity"
  response="$(curl -fsSL -X POST "$BOOTSTRAP_URL" \
    -H 'Content-Type: application/json' \
    --data "$payload")"

  mkdir -p "$DATA_DIR"
  chmod 0755 "$DATA_DIR"
  printf '%s\n' "$response" > "${DATA_DIR}/bootstrap-response.json"
  chmod 0600 "${DATA_DIR}/bootstrap-response.json"

  # MVP note: production installer should parse JSON with jq or an embedded
  # static helper. This shell skeleton expects the backend response to be saved
  # for the node daemon, which can complete config validation on first start.
}

write_identity_placeholder() {
  if [[ -f "$IDENTITY_FILE" ]]; then
    log "identity already exists: $IDENTITY_FILE"
    return
  fi

  cat > "$IDENTITY_FILE" <<JSON
{
  "bootstrap_response_file": "${DATA_DIR}/bootstrap-response.json",
  "created_by_installer": true,
  "installer_version": "$INSTALLER_VERSION"
}
JSON
  chmod 0640 "$IDENTITY_FILE"
}

install_binary_placeholder() {
  # During MVP research, install a placeholder binary that explains what is
  # missing. The real installer will download and verify a release artifact.
  cat > "${INSTALL_DIR}/${SERVICE_NAME}" <<'SH'
#!/usr/bin/env sh
if [ "$1" = "--version" ]; then
  echo "xaccel-node placeholder 0.1.0"
  exit 0
fi
if [ "$1" = "--check-config" ]; then
  test -f "$2" && exit 0
  echo "config not found: $2" >&2
  exit 1
fi
echo "xaccel-node binary is not installed yet. Replace this placeholder with the Rust daemon." >&2
sleep 3600
SH
  chmod 0755 "${INSTALL_DIR}/${SERVICE_NAME}"
}

write_config() {
  mkdir -p "$CONFIG_DIR" "$LOG_DIR"
  chmod 0755 "$CONFIG_DIR" "$LOG_DIR"
  cat > "$CONFIG_FILE" <<EOF
[identity]
identity_file = "$IDENTITY_FILE"

[runtime]
data_dir = "$DATA_DIR"
log_dir = "$LOG_DIR"
health_addr = "127.0.0.1:9876"
channel = "$CHANNEL"

[bootstrap]
response_file = "${DATA_DIR}/bootstrap-response.json"
EOF
  chmod 0644 "$CONFIG_FILE"
}

write_systemd_unit() {
  cat > "$SYSTEMD_UNIT" <<EOF
[Unit]
Description=XAccel Linux Acceleration Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart=${INSTALL_DIR}/${SERVICE_NAME} --config ${CONFIG_FILE}
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=3
LimitNOFILE=1048576
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN CAP_NET_RAW
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
}

open_firewall_if_requested() {
  [[ "$OPEN_FIREWALL" == "1" ]] || return 0
  log "firewall opening is requested, but port parsing depends on backend bootstrap response"
  log "MVP installer leaves firewall unchanged; open node TCP/UDP port manually"
}

enable_service() {
  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME"
  systemctl restart "$SERVICE_NAME"
}

health_check() {
  log "service started; health endpoint will become useful after real node binary is installed"
  systemctl --no-pager --full status "$SERVICE_NAME" || true
}

main() {
  preflight
  log "installer=${INSTALLER_VERSION} channel=${CHANNEL} arch=$(detect_arch)"
  if [[ "$DRY_RUN" == "1" ]]; then
    log "dry-run passed"
    exit 0
  fi

  bootstrap
  write_identity_placeholder
  install_binary_placeholder
  write_config
  write_systemd_unit
  open_firewall_if_requested
  enable_service
  health_check

  log "installed"
  log "service: systemctl status ${SERVICE_NAME}"
  log "logs: journalctl -u ${SERVICE_NAME} -f"
  log "config: ${CONFIG_FILE}"
}

main "$@"
