#!/usr/bin/env bash
set -Eeuo pipefail

INSTALLER_VERSION="0.32.0"
SERVICE_NAME="xaccel-node"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/xaccel-node"
DATA_DIR="/var/lib/xaccel-node"
LOG_DIR="/var/log/xaccel-node"
SYSTEMD_UNIT="/etc/systemd/system/${SERVICE_NAME}.service"
IDENTITY_FILE="${DATA_DIR}/identity.json"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
HEALTH_URL="http://127.0.0.1:9876/health"
GITHUB_REPO="xinbaopiaoliang-ui/cll"
RELEASE_BASE_URL="https://github.com/${GITHUB_REPO}/releases/latest/download"

BOOTSTRAP_URL=""
BOOTSTRAP_TOKEN=""
STANDALONE="0"
NODE_ID=""
PANEL_URL=""
SERVER_IP=""
LISTEN_IP="0.0.0.0"
SERVER_PORT=""
NODE_SECRET=""
CONFIG_REVISION="1"
CHANNEL="stable"
OPEN_FIREWALL="0"
DRY_RUN="0"
ARTIFACT_URL=""
SHA256_URL=""
ALLOW_PLACEHOLDER="0"
ENABLE_CONTROL_PLANE="0"

usage() {
  cat <<'USAGE'
Usage:
  install.sh --bootstrap-url URL --bootstrap-token TOKEN [options]
  install.sh --standalone --node-id ID --panel-url URL --server-ip IP --server-port PORT [options]

Options:
  --bootstrap-url URL     Backend bootstrap API URL.
  --bootstrap-token TOKEN One-time token generated by the backend.
  --standalone            Install without backend bootstrap. Useful before the panel API exists.
  --node-id ID            Node ID for standalone mode.
  --panel-url URL         Backend base URL for standalone mode.
  --server-ip IP          Node server IP for standalone mode.
  --listen-ip IP          Local listener bind IP. Default: 0.0.0.0.
  --server-port PORT      Node server port for standalone mode.
  --node-secret SECRET    Optional node secret for standalone mode.
  --channel CHANNEL       Release channel. Default: stable.
  --artifact-url URL      Override xaccel-node tar.gz download URL.
  --sha256-url URL        Override xaccel-node sha256 download URL.
  --allow-placeholder     Install placeholder service if release download is unavailable.
  --enable-control-plane  Enable daemon reports to --panel-url. Standalone mode defaults off.
  --open-firewall         Try to open the node port with ufw/firewalld.
  --dry-run               Run preflight only and print planned actions.
  -h, --help              Show this help.
USAGE
}

log() {
  printf '[xaccel-installer] %s\n' "$*"
}

fail() {
  printf '[xaccel-installer] ERROR: %s\n' "$*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bootstrap-url)
      BOOTSTRAP_URL="${2:-}"
      shift 2
      ;;
    --bootstrap-token)
      BOOTSTRAP_TOKEN="${2:-}"
      shift 2
      ;;
    --standalone)
      STANDALONE="1"
      shift
      ;;
    --node-id)
      NODE_ID="${2:-}"
      shift 2
      ;;
    --panel-url)
      PANEL_URL="${2:-}"
      shift 2
      ;;
    --server-ip)
      SERVER_IP="${2:-}"
      shift 2
      ;;
    --listen-ip)
      LISTEN_IP="${2:-}"
      shift 2
      ;;
    --server-port)
      SERVER_PORT="${2:-}"
      shift 2
      ;;
    --node-secret)
      NODE_SECRET="${2:-}"
      shift 2
      ;;
    --channel)
      CHANNEL="${2:-}"
      shift 2
      ;;
    --artifact-url)
      ARTIFACT_URL="${2:-}"
      shift 2
      ;;
    --sha256-url)
      SHA256_URL="${2:-}"
      shift 2
      ;;
    --allow-placeholder)
      ALLOW_PLACEHOLDER="1"
      shift
      ;;
    --enable-control-plane)
      ENABLE_CONTROL_PLANE="1"
      shift
      ;;
    --open-firewall)
      OPEN_FIREWALL="1"
      shift
      ;;
    --dry-run)
      DRY_RUN="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

require_root() {
  [[ "$(id -u)" == "0" ]] || fail "please run as root"
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "x86_64" ;;
    aarch64|arm64) echo "aarch64" ;;
    *) fail "unsupported arch: $(uname -m)" ;;
  esac
}

detect_ips() {
  ip -o -4 addr show scope global | awk '{ split($4, a, "/"); print a[1] }' | paste -sd, -
}

detect_ips_json() {
  ip -o -4 addr show scope global |
    awk '
      BEGIN { printf "["; first=1 }
      {
        split($4, a, "/")
        if (!first) { printf "," }
        printf "\"%s\"", a[1]
        first=0
      }
      END { printf "]" }
    '
}

preflight() {
  require_root
  command -v systemctl >/dev/null 2>&1 || fail "systemd is required"
  command -v ip >/dev/null 2>&1 || fail "iproute2 is required"
  command -v curl >/dev/null 2>&1 || fail "curl is required"
  command -v tar >/dev/null 2>&1 || fail "tar is required"
  [[ -n "$LISTEN_IP" ]] || fail "--listen-ip must not be empty"

  if [[ "$STANDALONE" == "1" ]]; then
    [[ -n "$NODE_ID" ]] || fail "--node-id is required in standalone mode"
    [[ -n "$PANEL_URL" ]] || fail "--panel-url is required in standalone mode"
    [[ -n "$SERVER_IP" ]] || fail "--server-ip is required in standalone mode"
    [[ -n "$SERVER_PORT" ]] || fail "--server-port is required in standalone mode"
    [[ "$SERVER_PORT" =~ ^[0-9]+$ ]] || fail "--server-port must be numeric"
    (( SERVER_PORT >= 1 && SERVER_PORT <= 65535 )) || fail "--server-port must be 1-65535"
    return
  fi

  [[ -n "$BOOTSTRAP_URL" ]] || fail "--bootstrap-url is required"
  [[ -n "$BOOTSTRAP_TOKEN" ]] || fail "--bootstrap-token is required"
}

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

json_string_field() {
  local file key
  file="$1"
  key="$2"
  sed -n "s/.*\"${key}\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$file" | head -n 1
}

json_number_field() {
  local file key
  file="$1"
  key="$2"
  sed -n "s/.*\"${key}\"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p" "$file" | head -n 1
}

load_bootstrap_response_vars() {
  local file
  file="${DATA_DIR}/bootstrap-response.json"
  [[ -f "$file" ]] || fail "bootstrap response missing: $file"

  NODE_ID="$(json_number_field "$file" "node_id")"
  NODE_SECRET="$(json_string_field "$file" "node_secret")"
  PANEL_URL="$(json_string_field "$file" "panel_url")"
  SERVER_IP="$(json_string_field "$file" "server_ip")"
  SERVER_PORT="$(json_number_field "$file" "server_port")"
  CONFIG_REVISION="$(json_number_field "$file" "config_revision")"
  CONFIG_REVISION="${CONFIG_REVISION:-1}"

  [[ -n "$NODE_ID" ]] || fail "bootstrap response missing node_id"
  [[ -n "$NODE_SECRET" ]] || fail "bootstrap response missing node_secret"
  [[ -n "$PANEL_URL" ]] || fail "bootstrap response missing panel_url"
  [[ -n "$SERVER_IP" ]] || fail "bootstrap response missing server_ip"
  [[ -n "$SERVER_PORT" ]] || fail "bootstrap response missing server_port"
  (( SERVER_PORT >= 1 && SERVER_PORT <= 65535 )) || fail "bootstrap response server_port must be 1-65535"
  (( CONFIG_REVISION >= 1 )) || fail "bootstrap response config_revision must be positive"
}

bootstrap() {
  local hostname arch kernel ips_json payload response
  hostname="$(hostname)"
  arch="$(detect_arch)"
  kernel="$(uname -r)"
  ips_json="$(detect_ips_json)"

  payload=$(
    cat <<JSON
{
  "bootstrap_token": "$(json_escape "$BOOTSTRAP_TOKEN")",
  "hostname": "$(json_escape "$hostname")",
  "os": "linux",
  "arch": "$(json_escape "$arch")",
  "kernel": "$(json_escape "$kernel")",
  "ips": $ips_json,
  "installer_version": "$INSTALLER_VERSION"
}
JSON
  )

  log "bootstrap node identity"
  response="$(curl -fsSL -X POST "$BOOTSTRAP_URL" \
    -H 'Content-Type: application/json' \
    --data "$payload")"

  mkdir -p "$DATA_DIR"
  chmod 0755 "$DATA_DIR"
  printf '%s\n' "$response" > "${DATA_DIR}/bootstrap-response.json"
  chmod 0600 "${DATA_DIR}/bootstrap-response.json"

  # MVP note: production installer should parse JSON with jq or an embedded
  # static helper. This shell skeleton expects the backend response to be saved
  # for the node daemon, which can complete config validation on first start.
}

bootstrap_standalone() {
  local secret
  secret="$NODE_SECRET"
  if [[ -z "$secret" ]]; then
    if command -v openssl >/dev/null 2>&1; then
      secret="$(openssl rand -base64 32)"
    else
      secret="standalone-$(date +%s)-$NODE_ID"
    fi
  fi

  log "write standalone bootstrap response"
  mkdir -p "$DATA_DIR"
  chmod 0755 "$DATA_DIR"
  cat > "${DATA_DIR}/bootstrap-response.json" <<JSON
{
  "node_id": $NODE_ID,
  "node_secret": "$(json_escape "$secret")",
  "panel_url": "$(json_escape "$PANEL_URL")",
  "server_ip": "$(json_escape "$SERVER_IP")",
  "server_port": $SERVER_PORT,
  "config_revision": 1,
  "release": {
      "version": "0.32.0",
    "manifest_url": ""
  },
  "standalone": true
}
JSON
  chmod 0600 "${DATA_DIR}/bootstrap-response.json"
}

read_identity_secret() {
  [[ -f "$IDENTITY_FILE" ]] || return 0
  sed -n 's/.*"node_secret": *"\([^"]*\)".*/\1/p' "$IDENTITY_FILE" | head -n 1
}

reuse_existing_identity_secret() {
  local existing_secret
  if [[ "$STANDALONE" != "1" || -n "$NODE_SECRET" || ! -f "$IDENTITY_FILE" ]]; then
    return 0
  fi

  existing_secret="$(read_identity_secret)"
  if [[ -n "$existing_secret" ]]; then
    NODE_SECRET="$existing_secret"
    log "reuse existing node secret from $IDENTITY_FILE"
  fi
}

write_identity_placeholder() {
  if [[ -f "$IDENTITY_FILE" ]]; then
    log "update existing identity: $IDENTITY_FILE"
  else
    log "write identity: $IDENTITY_FILE"
  fi

  if [[ "$STANDALONE" == "1" && -z "$NODE_SECRET" ]]; then
    NODE_SECRET="$(sed -n 's/.*"node_secret": "\([^"]*\)".*/\1/p' "${DATA_DIR}/bootstrap-response.json" | head -n 1)"
  fi

  if [[ "$STANDALONE" == "1" && -z "$NODE_SECRET" ]]; then
    fail "node secret is required to write standalone identity"
  fi

  cat > "$IDENTITY_FILE" <<JSON
{
  "node_id": ${NODE_ID:-null},
  "panel_url": "$(json_escape "$PANEL_URL")",
  "node_secret": "$(json_escape "$NODE_SECRET")",
  "bootstrap_response_file": "${DATA_DIR}/bootstrap-response.json",
  "created_by_installer": true,
  "installer_version": "$INSTALLER_VERSION"
}
JSON
  chmod 0640 "$IDENTITY_FILE"
}

install_binary_placeholder() {
  # During MVP research, install a placeholder binary that explains what is
  # missing. The real installer will download and verify a release artifact.
  cat > "${INSTALL_DIR}/${SERVICE_NAME}" <<'SH'
#!/usr/bin/env sh
if [ "$1" = "--version" ]; then
  echo "xaccel-node placeholder 0.1.0"
  exit 0
fi
if [ "$1" = "--check-config" ]; then
  test -f "$2" && exit 0
  echo "config not found: $2" >&2
  exit 1
fi
echo "xaccel-node binary is not installed yet. Replace this placeholder with the Rust daemon." >&2
sleep 3600
SH
  chmod 0755 "${INSTALL_DIR}/${SERVICE_NAME}"
}

install_binary_release() {
  local arch artifact_name artifact_url sha_url tmp_dir tar_file sha_file extracted_bin
  arch="$(detect_arch)"
  artifact_name="xaccel-node-linux-${arch}.tar.gz"
  artifact_url="${ARTIFACT_URL:-${RELEASE_BASE_URL}/${artifact_name}}"
  sha_url="${SHA256_URL:-${artifact_url}.sha256}"
  tmp_dir="$(mktemp -d)"
  tar_file="${tmp_dir}/${artifact_name}"
  sha_file="${tar_file}.sha256"

  log "download node release: ${artifact_url}"
  if ! curl -fsSL "$artifact_url" -o "$tar_file"; then
    rm -rf "$tmp_dir"
    if [[ "$ALLOW_PLACEHOLDER" == "1" ]]; then
      log "release download failed; installing placeholder because --allow-placeholder is set"
      install_binary_placeholder
      return 0
    fi
    fail "failed to download release artifact. Create a GitHub Release first, or pass --allow-placeholder for installer-only testing"
  fi

  log "download checksum: ${sha_url}"
  if curl -fsSL "$sha_url" -o "$sha_file"; then
    if command -v sha256sum >/dev/null 2>&1; then
      (cd "$tmp_dir" && sha256sum -c "$(basename "$sha_file")")
    elif command -v shasum >/dev/null 2>&1; then
      (cd "$tmp_dir" && shasum -a 256 -c "$(basename "$sha_file")")
    else
      rm -rf "$tmp_dir"
      fail "sha256sum or shasum is required to verify release artifact"
    fi
  else
    rm -rf "$tmp_dir"
    fail "failed to download sha256 file for release artifact"
  fi

  tar -xzf "$tar_file" -C "$tmp_dir"
  extracted_bin="$(find "$tmp_dir" -type f -name "$SERVICE_NAME" | head -n 1)"
  [[ -n "$extracted_bin" ]] || {
    rm -rf "$tmp_dir"
    fail "release artifact does not contain ${SERVICE_NAME}"
  }

  install -m 0755 "$extracted_bin" "${INSTALL_DIR}/${SERVICE_NAME}"
  rm -rf "$tmp_dir"
  log "installed ${INSTALL_DIR}/${SERVICE_NAME}"
}

write_config() {
  local control_enabled
  control_enabled="true"
  if [[ "$STANDALONE" == "1" && "$ENABLE_CONTROL_PLANE" != "1" ]]; then
    control_enabled="false"
  fi

  mkdir -p "$CONFIG_DIR" "$LOG_DIR"
  chmod 0755 "$CONFIG_DIR" "$LOG_DIR"
  cat > "$CONFIG_FILE" <<EOF
[identity]
identity_file = "$IDENTITY_FILE"

[runtime]
data_dir = "$DATA_DIR"
log_dir = "$LOG_DIR"
health_addr = "127.0.0.1:9876"
channel = "$CHANNEL"

[bootstrap]
response_file = "${DATA_DIR}/bootstrap-response.json"

[control]
enabled = ${control_enabled}
config_revision = ${CONFIG_REVISION}
request_timeout_sec = 5
config_poll_interval_sec = 30

[report]
interval_sec = 30
traffic_batch_sec = 60
metrics_interval_sec = 15
EOF

  if [[ -n "$SERVER_IP" && -n "$SERVER_PORT" ]]; then
    local network_tag
    network_tag="bootstrap"
    if [[ "$STANDALONE" == "1" ]]; then
      network_tag="standalone"
    fi
    cat >> "$CONFIG_FILE" <<EOF

[network]
server_ip = "$SERVER_IP"
listen_ip = "$LISTEN_IP"
server_port = $SERVER_PORT
relay_server_ip = ""
relay_server_port = 0
is_support_ipv6 = false
disable_quic = false
area = "UNKNOWN"
bandwidth_quality = "normal"
tag = "$network_tag"

[network.operator_ips]
telecom_ip = ""
mobile_ip = ""
unicom_ip = ""
EOF
  fi

  chmod 0644 "$CONFIG_FILE"
}

write_systemd_unit() {
  cat > "$SYSTEMD_UNIT" <<EOF
[Unit]
Description=XAccel Linux Acceleration Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart=${INSTALL_DIR}/${SERVICE_NAME} --config ${CONFIG_FILE}
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=3
LimitNOFILE=1048576
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN CAP_NET_RAW
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
}

open_firewall_if_requested() {
  [[ "$OPEN_FIREWALL" == "1" ]] || return 0
  if [[ -z "$SERVER_PORT" ]]; then
    log "firewall opening is requested, but server port is unknown"
    return 0
  fi

  if command -v ufw >/dev/null 2>&1; then
    ufw allow "${SERVER_PORT}/tcp" || true
    ufw allow "${SERVER_PORT}/udp" || true
    return 0
  fi

  if command -v firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --permanent --add-port="${SERVER_PORT}/tcp" || true
    firewall-cmd --permanent --add-port="${SERVER_PORT}/udp" || true
    firewall-cmd --reload || true
    return 0
  fi

  log "no supported firewall manager found; open TCP/UDP ${SERVER_PORT} manually"
}

enable_service() {
  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME"
  systemctl restart "$SERVICE_NAME"
}

health_check() {
  log "service started; health endpoint will become useful after real node binary is installed"
  systemctl --no-pager --full status "$SERVICE_NAME" || true
}

main() {
  preflight
  log "installer=${INSTALLER_VERSION} channel=${CHANNEL} arch=$(detect_arch)"
  if [[ "$DRY_RUN" == "1" ]]; then
    log "dry-run passed"
    exit 0
  fi

  reuse_existing_identity_secret
  if [[ "$STANDALONE" == "1" ]]; then
    bootstrap_standalone
  else
    bootstrap
  fi

  load_bootstrap_response_vars

  write_identity_placeholder
  install_binary_release
  write_config
  write_systemd_unit
  open_firewall_if_requested
  enable_service
  health_check

  log "installed"
  log "service: systemctl status ${SERVICE_NAME}"
  log "logs: journalctl -u ${SERVICE_NAME} -f"
  log "config: ${CONFIG_FILE}"
}

main "$@"
